---
regions:
  - us-east-1
  - us-west-2
  - eu-west-1
  - ap-southeast-1
  - ap-southeast-2

cloud_formation_root: "~/Code/src/github.com/GetStream/stream-puppet/cloudformation"
stacks_dir: "~/Code/src/github.com/keyneston/cftool/examples"
